백터의 크기 
a=np.sqrt(a_x**2+a_y**2+a_z**2)=np.sqrt(np.sum(a**2))=a_magnitude
<두 벡터의 스칼라곱> 내적 dot 사욯하면 바로 각각의 위치의 값들을 다 더한 갓이 나온다.(제곱해서 더한것을 루트씌운것)
벡터 a·벡터 b=a·b·cosθ=a_x*b_x+a_y*b_y+a_z*b_z
내적 값이 0이면 두 백터는 서로 수직한다 a·b=.a_x*b_x+a_y*b_y+a_z*b_z=0
같은 벡터 방향끼리 곱하면 1이 나온다. a·a=a_x**2+a_y**2+a_z**2=1
단위벡터 x·x=1/x·y=0

<두 벡터의 벡터곱>외적 cross를 사용하면 벡터의 위치가 나오는데 이를 크기로 정리를 해줘야한다.(제곱해서 더한것을 루트씌워야 한다)

ab = b-a
ab=ob-oa
ab #벡터값은 a에서 b로 이어지는 직선
ab면 a에서 b로 간다.
-oa=ao  o가 사이에서 이어준다
ab=aoob

round(변수,표현하고 싶은 자릿수)
시작하기 전에 주어진게 무엇인지에 따라 정리 달라짐
1.극좌표계일떄
2.직각좌표계일떄
3.벡터가 a=x+y+z식으로 주어지면 바로 array로 정의

사이값 θ 구하려면<내적> cosθ=벡터a·벡터b/a·b
a_magnitude=np.sqrt(np.sum(a**2))
b_magnitude=np.sqrt(np.sum(b**2))
cosθ(cos_theta)=np.dot(a,b)/a_magnitude·b_magnide
theta_radians=np.arccos(cos_theta)
np.round=np.degrees(theta_radians)

백터의 크기 구하기<외적> cross값이 나오면 sum을 하고 루트를 씌워서 정리를 한다.절대값느낌 
백터 c=백터 a X 벡터 b=단위벡터c·a·b·sinθ
cross_product_a_b=np.cross(a,b)
cross_product_magnitude=np.sqrt(np.sum(product**2))

In [1]:
import numpy as np #시작할때 꼭!!!!!!!!!!!!!!!

In [4]:
#극좌표계로 위치벡터 x,y성분 구하기
r = 25.0 # 거리, 미터
theta_degrees = 210 # 각도, 도

theta_radians = np.radians(theta_degrees) #라디안으로 정의해야 문제가 풀림(기본이 라디안이라서)
x = r * np.cos(theta_radians) #x=r*cos
y = r * np.sin(theta_radians) #y=r*sin

np.round(x,1), np.round(y,1)

(-21.7, -12.5)

In [37]:
r = 10 # 거리, 미터
theta_degrees = 30# 각도, 도

theta_radians = np.radians(theta_degrees) #라디안으로 정의해야 문제가 풀림(기본이 라디안이라서)
x = r * np.cos(theta_radians) #x=r*cos
y = r * np.sin(theta_radians) #y=r*sin

np.round(x,1), np.round(y,1)

(8.7, 5.0)

In [43]:
#벡터a,벡터b의 극좌표계로 벡터 c의 값,직교좌표 구하기

a_magnitude=10
b_magnitude=4
theta_a_degrees=30
theta_b_degrees=70
theta_a_radians=np.radians(theta_a_degrees)
theta_b_radians=np.radians(theta_b_degrees)
a_x=a_magnitude*np.cos(theta_a_radians)
b_x=b_magnitude*np.cos(theta_b_radians)
a_y=a_magnitude*np.sin(theta_a_radians)
b_y=b_magnitude*np.sin(theta_b_radians)
c_x=a_x+b_x
c_y=a_y+b_y
c_magnitude=np.sqrt(c_x**2+c_y**2)

np.round(c_magnitude,2),c_x,c_y

(13.31, 10.028334611147063, 8.758770483143632)

In [ ]:
c_magnitude=np.sqrt(c_x**2+c_y**2)


In [7]:
# 벡터의 각도(아크탄젠트)를 라디안으로 계산
angle_radians = np.arctan2(c_y, c_x)

# 라디안을 도로 변환
angle_degrees = np.degrees(angle_radians)

# 각도를 소숫점 셋째자리에서 반올림
angle_degrees_rounded = np.round(angle_degrees, 2)

angle_degrees_rounded

102.16

In [ ]:
# a 벡터의 크기?
np.sqrt(7**2 + 4**2 + (-1) **2) #위 아래가 같은 식
np.sqrt(np.sum(a**2))          #아래 있는 np.sum이 걍 벡터 더하는 식임

In [6]:
#벡터가 a=x+y+z식이나 좌표로 주어지면 바로 array로 정의
a=np.array([7,4,-1])   #array로 묶어서벡터표현 
b=np.array([2,-3,5]) 
c=np.array([-5,1,-3])
d=a-2*b+3*c 
d

array([-12,  13, -20])

In [9]:
#벡터값정의내리기
ab=b-a #b에서 a로 이어지는 벡터
ab

array([-5, -7,  6])

In [10]:
#두 벡터의 사이값θ 계산(스칼라곱 사용해서 cos값 구하기) 
a=np.array([1,1,0])
b=np.array([0,1,-1])
a_magnitude=np.sqrt(np.sum(a**2))  #magnitude로 정의 내려도 되고 바로 식으로 쭉 나열해도 ㄱㅊ
b_magnitude=np.sqrt(np.sum(b**2))  #cos_theta=np.dot(a,b)/(np.sqrt(np.sum(a**2))*np.sqrt(np.sum(b**2)))
cos_theta=np.dot(a,b)/(a_magnitude*b_magnitude)  #곱하기는 괄호로 묶어야 함!!!
theta_radians=np.arccos(cos_theta)
np.round(np.degrees(theta_radians),2)


60.0

In [26]:
a=np.array([1,1,2])
b=np.array([2,3,5])
a_magnitude=np.sqrt(np.sum(a**2))  #magnitude로 정의 내려도 되고 바로 식으로 쭉 나열해도 ㄱㅊ
b_magnitude=np.sqrt(np.sum(b**2))  #cos_theta=np.dot(a,b)/(np.sqrt(np.sum(a**2))*np.sqrt(np.sum(b**2)))
cos_theta=np.dot(a,b)/(a_magnitude*b_magnitude)  #곱하기는 괄호로 묶어야 함!!!
theta_radians=np.arccos(cos_theta)
np.round(np.degrees(theta_radians),2)


6.59

In [19]:
#벡터의 곱으로 벡터의 크기 구하기(크기 구해서 절댓값 씌우는 느낌)
a=np.array([2,1,0])
b=np.array([0,1,-3])
cross_product_a_b=np.cross(a,b)
cross_product_magnitute=np.sqrt(np.sum(cross_product_a_b**2))
np.round(cross_product_magnitute,2)

7.0

In [29]:
a=np.array([1,1,2])
b=np.array([2,3,5])
cross_product_a_b=np.cross(a,b)
cross_product_magnitute=np.sqrt(np.sum(cross_product_a_b**2))
triangle_area = cross_product_magnitute / 2
np.round(triangle_area,2)

0.87

In [11]:
#삼각형의 크기 벡터곱으로 벡터의 크기구함(평사의 넓이) 평사의 넓이/2=삼각형의 넓이
# 점 P, Q, R의 좌표
P = np.array([1, 3, 2])
Q = np.array([2, 0, 0])
R = np.array([0, 0, 4])

# 벡터 PQ와 PR 계산
PQ = Q - P #PQ=OQ-OP
PR = R - P #PR=OR-OP

# 벡터 PQ와 PR의 외적 계산
cross_product = np.cross(PQ, PR)

# 외적 벡터의 크기 계산
cross_product_magnitude = np.sqrt(np.sum(cross_product**2))

# 삼각형의 넓이는 외적 벡터의 크기의 절반
triangle_area = cross_product_magnitude / 2
np.round(triangle_area,2)

6.71

In [27]:
P = np.array([2,4,3])
Q = np.array([3, 0, 0])
R = np.array([0, 1,5])

# 벡터 PQ와 PR 계산
PQ = Q - P #PQ=OQ-OP
PR = R - P #PR=OR-OP

# 벡터 PQ와 PR의 외적 계산
cross_product = np.cross(PQ, PR)

# 외적 벡터의 크기 계산
cross_product_magnitude = np.sqrt(np.sum(cross_product**2))

# 삼각형의 넓이는 외적 벡터의 크기의 절반
triangle_area = cross_product_magnitude / 2
np.round(triangle_area,2)

10.32

In [16]:
from sympy import symbols, Eq, solve
#수직이 되는 벡터의 값을 b라 정의하고 주어진 벡터의 값과의 관계로 식 세우기
# 심볼 변수 정의
b_x, b_y = symbols('b_x b_y') #걍 곱한다.백터곱마냥 두개의 x,y의 계수 곱해요

# 주어진 조건을 바탕으로 방정식 설정
eq1 = Eq(3 * b_x - 4 * b_y, 0)  # a와 b가 수직이므로 a·b = 0
eq2 = Eq(b_x**2 + b_y**2, 1)    # b는 단위벡터이므로 b의 크기의 제곱은 1

# 연립방정식 풀이
solution = solve((eq1, eq2), (b_x, b_y))
solution

[(-4/5, -3/5), (4/5, 3/5)]

In [49]:
from sympy import symbols, Eq, solve
#수직이 되는 벡터의 값을 b라 정의하고 주어진 벡터의 값과의 관계로 식 세우기
# 심볼 변수 정의
b_x, b_y ,b_z = symbols('b_x b_y b_z') #걍 곱한다.백터곱마냥 두개의 x,y의 계수 곱해요

# 주어진 조건을 바탕으로 방정식 설정
eq1 = Eq(3 * b_x - 4 * b_y+ 0*b_z, 0)  # a와 b가 수직이므로 a·b = 0
eq2 = Eq(b_x**2 + b_y**2 + b_z**2, 1)
eq3 = Eq(b_x,0)  # b는 단위벡터이므로 b의 크기의 제곱은 1

# 연립방정식 풀이
solution = solve((eq1, eq2, eq3), (b_x, b_y, b_z))
solution

[(0, 0, -1), (0, 0, 1)]

In [24]:
#두 벡터에 수직인 벡터
a = np.array([1, 1, 0])
b = np.array([0, 1, -1])
c=np.cross(a,b)
v1 = np.array([1, 1, 1])
v2 = np.array([1, -1, 1])
v3 = np.array([1, -1, -1])
v4 = np.array([1, 1, -1])
cross_c_v1=np.cross(c,v1)
cross_c_v2=np.cross(c,v2)
cross_c_v3=np.cross(c,v3)
cross_c_v4=np.cross(c,v4)
dot_c_v1,dot_c_v2,dot_c_v3,dot_c_v4


(array([ 0,  2, -2]), array([2, 2, 0]), array([0, 0, 0]), array([-2,  0, -2]))